services:
    eikona_media.contao.password_policy.policy_service:
        class: EikonaMedia\Contao\PasswordPolicy\Service\PasswordPolicyService
        arguments:
            - '@translator'
        public: true
